// Turns the hand-built sprite map into src/sprites.css and src/data/sprites.js.
//
//   node tools/import-sprites.mjs                     # rebuild from tools/item-atlas.png
//   node tools/import-sprites.mjs --sprites ~/dump    # re-pack the atlas from a sprite dump
//
// The ids in a Tibia sprite dump are *sprite indices*, not item ids: the file
// called 2400.png is whatever happened to be 2400th in the .spr, not the magic
// sword. An earlier version of this script mapped them by looking names up in
// OTServ's items.xml, which produced a Mastermind Shield that rendered as a
// bunch of bananas. There is no lookup table that fixes this, so the mapping in
// tools/sprite-map.json was built by eye — contact sheets of the dump, then
// every item rendered with its own name underneath until the names matched the
// pictures. Treat that file as source, not as output.
//
// The 161 mapped sprites are packed into one 512x352 atlas and embedded as a
// single data URI, which is a tenth the size of 161 separate ones and survives
// being inlined into the single-file artifact build. Items with no sprite keep
// their emoji, so a partial map is fine.
import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ITEMS } from '../src/data/items.js';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const arg = (name, fallback) => {
  const i = process.argv.indexOf(`--${name}`);
  return i === -1 ? fallback : process.argv[i + 1];
};

const mapPath = join(root, 'tools/sprite-map.json');
const atlasPath = join(root, 'tools/item-atlas.png');
const COLS = 16;

const map = JSON.parse(readFileSync(mapPath, 'utf8'));
const items = Object.keys(map).filter((k) => !k.startsWith('_')).sort();

const unknown = items.filter((id) => !ITEMS[id]);
if (unknown.length) {
  console.error(`sprite-map.json names items that do not exist: ${unknown.join(', ')}`);
  process.exit(1);
}

// Re-packing needs the dump and Pillow; the committed atlas covers the common
// case of "I changed nothing, rebuild the CSS".
const dump = arg('sprites', null);
if (dump) {
  const dir = resolve(dump);
  const have = new Set(readdirSync(dir).filter((f) => f.endsWith('.png')).map((f) => f.slice(0, -4)));
  const missing = items.filter((id) => !have.has(String(map[id])));
  if (missing.length) {
    console.error(`dump has no sprite for: ${missing.map((id) => `${id}=${map[id]}`).join(', ')}`);
    process.exit(1);
  }
  const rows = Math.ceil(items.length / COLS);
  execFileSync('python3', ['-c', `
import json, sys
from PIL import Image
src, out, cols = sys.argv[1], sys.argv[2], ${COLS}
items = json.loads(sys.argv[3]); mapping = json.loads(sys.argv[4])
atlas = Image.new('RGBA', (cols * 32, ${rows} * 32), (0, 0, 0, 0))
for n, item in enumerate(items):
    sp = Image.open(f'{src}/{mapping[item]}.png').convert('RGBA')
    atlas.paste(sp, (n % cols * 32, n // cols * 32), sp)
atlas.save(out, optimize=True)
`, dir, atlasPath, JSON.stringify(items), JSON.stringify(map)], { stdio: 'inherit' });
  console.log(`packed ${items.length} sprites into ${atlasPath}`);
}

if (!existsSync(atlasPath)) {
  console.error(`no atlas at ${atlasPath} — pass --sprites <dump> to pack one`);
  process.exit(1);
}
const atlas = readFileSync(atlasPath);
const uri = `data:image/png;base64,${atlas.toString('base64')}`;

const rows = Math.ceil(items.length / COLS);
const at = (n, div) => {
  const x = ((n % COLS) * 32) / div;
  const y = (Math.floor(n / COLS) * 32) / div;
  return `-${x}px -${y}px`;
};
// Half-size copies for the 16px inline glyphs: scaling an atlas down means
// scaling its offsets too, so each item needs a second rule rather than one
// shared `background-size`.
const full = items.map((id, n) => `.spr-${id}{background-position:${at(n, 1)}}`);
const half = items.map((id, n) => `.inline-sprite.spr-${id}{background-position:${at(n, 2)}}`);

const css = `/* Item sprites, generated by tools/import-sprites.mjs — do not edit.
   ${items.length} of ${Object.keys(ITEMS).length} items; the rest fall back to their emoji.
   See the Sprites section of README.md. */
.sprite { display: block; width: 32px; height: 32px; image-rendering: pixelated;
  background-repeat: no-repeat;
  background-image: url(${uri}); }
.inline-sprite.sprite {
  display: inline-block; width: 16px; height: 16px; vertical-align: -3px;
  background-size: ${(COLS * 32) / 2}px ${(rows * 32) / 2}px;
}
${full.join('\n')}
${half.join('\n')}
`;
writeFileSync(join(root, 'src/sprites.css'), css);

const js = `// Which items have a sprite in src/sprites.css.
//
// Generated by tools/import-sprites.mjs — see the Sprites section of README.md.
// Empty means "emoji everywhere", which is the default and renders fine.
export const SPRITE_IDS = new Set([
${items.map((id) => `  '${id}',`).join('\n')}
]);

export const hasSprite = (itemId) => SPRITE_IDS.has(itemId);
`;
writeFileSync(join(root, 'src/data/sprites.js'), js);

const withoit = Object.keys(ITEMS).filter((id) => !map[id]);
console.log(`wrote src/sprites.css (${(css.length / 1024).toFixed(0)} KB) and src/data/sprites.js`);
console.log(`${items.length} items with sprites, ${withoit.length} on emoji: ${withoit.join(' ')}`);
