// Turns a folder of Tibia item sprites into src/sprites.css.
//
//   node tools/import-sprites.mjs --sprites ~/tibia-sprites --otserv /tmp/otserv
//
// The sprite dumps floating around name each PNG after its Tibia item id
// (2400.png is the magic sword), and OTServ's items.xml maps names to those
// ids — so the two together give us a name-based mapping for free.
//
// Sprites are embedded as data URIs rather than packed into a sheet: the bytes
// are copied verbatim (no decode, no re-encode, no quality loss), it survives
// being bundled into a single-file artifact, and adding an item is one re-run.
// Items with no sprite keep their emoji, so a partial set is fine.
import { readFileSync, readdirSync, writeFileSync, existsSync } from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ITEMS } from '../src/data/items.js';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const arg = (name, fallback) => {
  const i = process.argv.indexOf(`--${name}`);
  return i === -1 ? fallback : process.argv[i + 1];
};
const spriteDir = resolve(arg('sprites', '/tmp/tibia-sprites'));
const otserv = resolve(arg('otserv', '/tmp/otserv'));

// Items that postdate this sprite set (potions arrived in 8.0, creature
// products later still). Where the era had something equivalent, borrow it;
// the rest keep their emoji.
const SUBSTITUTE = {
  health_potion: 2006, // vial
  strong_health_potion: 2006,
  great_health_potion: 2006,
  mana_potion: 2006,
  strong_mana_potion: 2006,
  great_mana_potion: 2006,
  rune_light_healing: 2265, // intense healing rune
  broadsword: 2413, // "broad sword" in items.xml
  royal_crossbow: 2455, // crossbow
  rainbow_trout: 2667, // fish
};

const xmlPath = join(otserv, 'data/items/items.xml');
if (!existsSync(xmlPath)) {
  console.error(`no items.xml at ${xmlPath} — clone OpenTibiaArchives/otserv and pass --otserv`);
  process.exit(1);
}
const xml = readFileSync(xmlPath, 'utf8');
const idByName = new Map();
for (const m of xml.matchAll(/<item id="(\d+)"[^>]*name="([^"]+)"/g)) {
  const name = m[2].toLowerCase();
  if (!idByName.has(name)) idByName.set(name, Number(m[1])); // lowest id wins
}

const available = new Set(
  readdirSync(spriteDir).filter((f) => f.endsWith('.png')).map((f) => Number(f.slice(0, -4))),
);

const rules = [];
const skipped = [];
let bytes = 0;

for (const [id, item] of Object.entries(ITEMS)) {
  const tibiaId = SUBSTITUTE[id] ?? idByName.get(item.name.toLowerCase());
  if (!tibiaId || !available.has(tibiaId)) {
    skipped.push(item.name);
    continue;
  }
  const png = readFileSync(join(spriteDir, `${tibiaId}.png`));
  bytes += png.length;
  rules.push({ id, tibiaId, name: item.name, data: png.toString('base64') });
}

const css = `/* Generated by tools/import-sprites.mjs — do not edit by hand.
   ${rules.length} Tibia item sprites, 32x32, embedded as data URIs.
   Item ids come from OTServ's items.xml; sprite files are named after them. */
.sprite { display: block; width: 32px; height: 32px; image-rendering: pixelated;
  background-repeat: no-repeat; background-position: center; }
${rules.map((r) => `.spr-${r.id} { background-image: url(data:image/png;base64,${r.data}); } /* ${r.name} (${r.tibiaId}) */`).join('\n')}
`;
writeFileSync(join(root, 'src/sprites.css'), css);

const registry = `// Generated by tools/import-sprites.mjs — do not edit by hand.
//
// Which items have a sprite in src/sprites.css. Anything missing falls back to
// the emoji on the item itself, so a partial set renders fine.
export const SPRITE_IDS = new Set([
${rules.map((r) => `  '${r.id}',`).join('\n')}
]);

export const hasSprite = (itemId) => SPRITE_IDS.has(itemId);
`;
writeFileSync(join(root, 'src/data/sprites.js'), registry);

console.log(`wrote ${rules.length} sprites (${(bytes / 1024).toFixed(0)} KB raw, `
  + `${(css.length / 1024).toFixed(0)} KB of CSS) from ${spriteDir}`);
if (skipped.length) console.log(`no sprite for ${skipped.length}: ${skipped.join(', ')}`);
